# Generated by Django 2.1.5 on 2019-03-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0020_auto_20170104_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='type',
            field=models.IntegerField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
